$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1397448870100.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"12d48d9a951e495ba20af0047d03a461",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2ad94424eb3f45a3bc20cc5c04c29d63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":80},
            "size":{
              "width":300,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88d10cd5f1554eb5948c07a8cc6366aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":80},
                "size":{
                  "width":300,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"78ee84e11c2c4ebaba0eb9bd897e84da",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":80},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open tel:555-1212 in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"tel:555-1212",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7fad8bff79aa42d38b9c3cf7bf9cb303",
          "label":"PopupStates",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":10,
              "y":140},
            "size":{
              "width":300,
              "height":220},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"fc66c8a019f54826b1d6250157eebb0c",
              "label":"Directions",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"98b996374e644613880b75381659c0c3",
                  "label":"",
                  "parentDynamicPanel":"7fad8bff79aa42d38b9c3cf7bf9cb303",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":260,
                      "y":10},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ccafcb714ca4a38944d0c550231a204",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fad8bff79aa42d38b9c3cf7bf9cb303",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":260,
                          "y":10},
                        "size":{
                          "width":30,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set PopupStates to Directions slide down out 500ms",
                              "panelsToStates":[{
                                  "panelPath":["7fad8bff79aa42d38b9c3cf7bf9cb303"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideDown",
                                        "duration":500},
                                      "compress":false}}}]},
{
                              "action":"wait",
                              "description":"Wait 1000 ms",
                              "waitTime":1000},
{
                              "action":"fadeWidget",
                              "description":"Hide PopupStates",
                              "objectsToFades":[{
                                  "objectPath":["7fad8bff79aa42d38b9c3cf7bf9cb303"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u4.png"}},
{
                  "id":"72d767aefad8467e8149aa28393b72b6",
                  "label":"",
                  "parentDynamicPanel":"7fad8bff79aa42d38b9c3cf7bf9cb303",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":300,
                      "height":150}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b4ce42c0dd284a2e809c3ad131af6c06",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fad8bff79aa42d38b9c3cf7bf9cb303",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":50},
                        "size":{
                          "width":300,
                          "height":150}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u6.png"}},
{
                  "id":"6d1b3dd2dfd44f45ba218357d7dda23c",
                  "label":"",
                  "parentDynamicPanel":"7fad8bff79aa42d38b9c3cf7bf9cb303",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":40,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":20}},
                  "adaptiveStyles":{
}},
{
                  "id":"c6296931302444ca96e6f4c54553e7c5",
                  "label":"",
                  "parentDynamicPanel":"7fad8bff79aa42d38b9c3cf7bf9cb303",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":40,
                      "y":20},
                    "size":{
                      "width":200,
                      "height":20}},
                  "adaptiveStyles":{
}},
{
                  "id":"35be95ace28145d18f74837ef20014fb",
                  "label":"",
                  "parentDynamicPanel":"7fad8bff79aa42d38b9c3cf7bf9cb303",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":30,
                      "y":200},
                    "size":{
                      "width":230,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d6312619b8984c90b8bb23d0a18f7b06",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fad8bff79aa42d38b9c3cf7bf9cb303",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":30,
                          "y":200},
                        "size":{
                          "width":230,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open https://www.google.ca/maps/place/4301+Rue+de+la+Roche/@45.527231,-73.5752139,17z/data=!3m1!4b1!4m2!3m1!1s0x4cc91bc573fc6d47:0xd14720373c8cff83 in Current Window",
                              "target":{
                                "targetType":"webUrl",
                                "urlLiteral":{
                                  "exprType":"stringLiteral",
                                  "value":"https://www.google.ca/maps/place/4301+Rue+de+la+Roche/@45.527231,-73.5752139,17z/data=!3m1!4b1!4m2!3m1!1s0x4cc91bc573fc6d47:0xd14720373c8cff83",
                                  "stos":[]},
                                "includeVariables":false},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"2f74c185cfcf45f19ef52a0d0f3281e4",
              "label":"Menu",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5c24ca5212b74fa8bb2673fce3daa3d0",
                  "label":"",
                  "parentDynamicPanel":"7fad8bff79aa42d38b9c3cf7bf9cb303",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":260,
                      "y":10},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d57d2d8b6064549a2e531772ed884af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fad8bff79aa42d38b9c3cf7bf9cb303",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":260,
                          "y":10},
                        "size":{
                          "width":30,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set PopupStates to Directions slide down out 500ms",
                              "panelsToStates":[{
                                  "panelPath":["7fad8bff79aa42d38b9c3cf7bf9cb303"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateOut":{
                                        "easing":"slideDown",
                                        "duration":500},
                                      "compress":false}}}]},
{
                              "action":"wait",
                              "description":"Wait 1000 ms",
                              "waitTime":1000},
{
                              "action":"fadeWidget",
                              "description":"Hide PopupStates",
                              "objectsToFades":[{
                                  "objectPath":["7fad8bff79aa42d38b9c3cf7bf9cb303"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u4.png"}},
{
                  "id":"e8e4168078774ed7967674bd0e48b320",
                  "label":"Content",
                  "parentDynamicPanel":"7fad8bff79aa42d38b9c3cf7bf9cb303",
                  "panelIndex":1,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"verticalAsNeeded",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"a1014ea5dc3d4ec29f9b0994c7cb8b07",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"e6c94ef7821c4d5daa6f15e5e99fb751",
                          "label":"",
                          "parentDynamicPanel":"e8e4168078774ed7967674bd0e48b320",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":300,
                              "height":144}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9cbd2b7cb7db4f368d475e18c76bffb9",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"e8e4168078774ed7967674bd0e48b320",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":300,
                                  "height":144}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"7d15d5f85e4841ceaf0735031754669a",
                          "label":"",
                          "parentDynamicPanel":"e8e4168078774ed7967674bd0e48b320",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":154},
                            "size":{
                              "width":300,
                              "height":144}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"db44d797fb8a4422852e8d5b7ff8a9be",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"e8e4168078774ed7967674bd0e48b320",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":0,
                                  "y":154},
                                "size":{
                                  "width":300,
                                  "height":144}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"b4600615ac0d4940a98533e8fc5dff47",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":300,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"751f19057c644d9f9243fd58c560e0d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":300,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u19.png"}},
{
          "id":"55c79ce132424a6496494799dac30252",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":140},
            "size":{
              "width":300,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"118be17bd11d4cb692ff843dded774f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":140},
                "size":{
                  "width":300,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set PopupStates to Directions slide up in 500ms show if hidden",
                      "panelsToStates":[{
                          "panelPath":["7fad8bff79aa42d38b9c3cf7bf9cb303"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"slideUp",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Bring PopupStates to Front ",
                      "panelPaths":[{
                          "panelPath":["7fad8bff79aa42d38b9c3cf7bf9cb303"],
                          "setOrderInfo":{
                            "bringToFront":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"3d73361805184860a5130c1a67d85633",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":200},
            "size":{
              "width":300,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fa83ec6048d4ead867f2dc379b51525",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":200},
                "size":{
                  "width":300,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set PopupStates to Directions slide up in 500ms show if hidden",
                      "panelsToStates":[{
                          "panelPath":["7fad8bff79aa42d38b9c3cf7bf9cb303"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "animateIn":{
                                "easing":"slideUp",
                                "duration":500},
                              "compress":false}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Bring PopupStates to Front ",
                      "panelPaths":[{
                          "panelPath":["7fad8bff79aa42d38b9c3cf7bf9cb303"],
                          "setOrderInfo":{
                            "bringToFront":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"ff8d0648ec5142d8a1f5c2ce9afadf29",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":85},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6943bbbbe68e470a853bc6e274375c14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":85},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u25.png"}},
{
          "id":"08b6201ce1da461b93ec02aaea51e835",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":260},
            "size":{
              "width":300,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52960015f2914cde9fdcd5e840279a34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":260},
                "size":{
                  "width":300,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Cupons in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"cupons.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"b73ec54c584346bd9bedbfecac54a7c3",
          "label":"EmailField",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":330},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a58b8697b97f40f18352c99fa16e1096",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":329},
            "size":{
              "width":80,
              "height":25},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb565c23e24c4b1c88a7c629608e28ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":329},
                "size":{
                  "width":80,
                  "height":25},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on EmailField equal to &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b73ec54c584346bd9bedbfecac54a7c3"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}},
{
                      "action":"setFunction",
                      "description":"Set text on EmailPanel equal to &quot;Thank you for signing up&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["c092cc261da54d77ac32599a95c05016"]},
{
                                "exprType":"stringLiteral",
                                "value":"Thank you for signing up",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u30.png"}},
{
          "id":"64417b7638f041a882d44d45146b8a41",
          "label":"EmailPanel",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":311},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c092cc261da54d77ac32599a95c05016",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":311},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2ad94424eb3f45a3bc20cc5c04c29d63":{
      "scriptId":"u0"},
    "88d10cd5f1554eb5948c07a8cc6366aa":{
      "scriptId":"u1"},
    "78ee84e11c2c4ebaba0eb9bd897e84da":{
      "scriptId":"u2"},
    "7fad8bff79aa42d38b9c3cf7bf9cb303":{
      "scriptId":"u3"},
    "98b996374e644613880b75381659c0c3":{
      "scriptId":"u4"},
    "1ccafcb714ca4a38944d0c550231a204":{
      "scriptId":"u5"},
    "72d767aefad8467e8149aa28393b72b6":{
      "scriptId":"u6"},
    "b4ce42c0dd284a2e809c3ad131af6c06":{
      "scriptId":"u7"},
    "6d1b3dd2dfd44f45ba218357d7dda23c":{
      "scriptId":"u8"},
    "c6296931302444ca96e6f4c54553e7c5":{
      "scriptId":"u9"},
    "35be95ace28145d18f74837ef20014fb":{
      "scriptId":"u10"},
    "d6312619b8984c90b8bb23d0a18f7b06":{
      "scriptId":"u11"},
    "5c24ca5212b74fa8bb2673fce3daa3d0":{
      "scriptId":"u12"},
    "7d57d2d8b6064549a2e531772ed884af":{
      "scriptId":"u13"},
    "e8e4168078774ed7967674bd0e48b320":{
      "scriptId":"u14"},
    "e6c94ef7821c4d5daa6f15e5e99fb751":{
      "scriptId":"u15"},
    "9cbd2b7cb7db4f368d475e18c76bffb9":{
      "scriptId":"u16"},
    "7d15d5f85e4841ceaf0735031754669a":{
      "scriptId":"u17"},
    "db44d797fb8a4422852e8d5b7ff8a9be":{
      "scriptId":"u18"},
    "b4600615ac0d4940a98533e8fc5dff47":{
      "scriptId":"u19"},
    "751f19057c644d9f9243fd58c560e0d8":{
      "scriptId":"u20"},
    "55c79ce132424a6496494799dac30252":{
      "scriptId":"u21"},
    "118be17bd11d4cb692ff843dded774f7":{
      "scriptId":"u22"},
    "3d73361805184860a5130c1a67d85633":{
      "scriptId":"u23"},
    "5fa83ec6048d4ead867f2dc379b51525":{
      "scriptId":"u24"},
    "ff8d0648ec5142d8a1f5c2ce9afadf29":{
      "scriptId":"u25"},
    "6943bbbbe68e470a853bc6e274375c14":{
      "scriptId":"u26"},
    "08b6201ce1da461b93ec02aaea51e835":{
      "scriptId":"u27"},
    "52960015f2914cde9fdcd5e840279a34":{
      "scriptId":"u28"},
    "b73ec54c584346bd9bedbfecac54a7c3":{
      "scriptId":"u29"},
    "a58b8697b97f40f18352c99fa16e1096":{
      "scriptId":"u30"},
    "fb565c23e24c4b1c88a7c629608e28ad":{
      "scriptId":"u31"},
    "64417b7638f041a882d44d45146b8a41":{
      "scriptId":"u32"},
    "c092cc261da54d77ac32599a95c05016":{
      "scriptId":"u33"}}});