$axure.loadCurrentPage({
  "url":"cupons.html",
  "generationDate":new Date(1397448870157.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b1704f0c264045219ee441f24838b9f3",
    "type":"Axure:Page",
    "name":"Cupons",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9a7333d1cf4c4afcb329b61357a2b9cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":300,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"573331fb8d804ea4881180d20b332507",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":300,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u19.png"}},
{
          "id":"dd712d68ca234be389d07b5c35439a87",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":80},
            "size":{
              "width":300,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a9f6c13ce8a473393bbc57609d8bd14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":80},
                "size":{
                  "width":300,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"845c328ec60b4d3bba9560c9bf0da61a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":80},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open tel:555-1212 in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"tel:555-1212",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b4a4a288ca324afdb9eb324f586fc09a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":85},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e97fac2b1414e4e87ef7afd1551e78f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":85},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u25.png"}},
{
          "id":"293f0987ade74df6b3d7502975e0bc3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":140},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d801f217a0b848e7b35a64614fc0fe1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":140},
                "size":{
                  "width":300,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cupons/u7.png"}},
{
          "id":"b15ad5972cbd48dba8bc378a4b3e5132",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":200},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7441a67193a49eda660d9bc9d19bcfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":200},
                "size":{
                  "width":300,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cupons/u7.png"}},
{
          "id":"62fdd26f81cf4a8cb4d358e6ea8e31ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":260},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc04efe6fe7a43e198c8f692b532b7eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":260},
                "size":{
                  "width":300,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cupons/u7.png"}},
{
          "id":"db0f3772b9284a01ad9f164e7f516842",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":320},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf46cf4c81bf4ad09c2be25fe5f6ccd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":320},
                "size":{
                  "width":300,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cupons/u7.png"}},
{
          "id":"4fe4db9de8c0448fb495bc481196d294",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":380},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b6761e22d894c5f985f1506a9fa11af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":380},
                "size":{
                  "width":300,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cupons/u7.png"}},
{
          "id":"2e9ffae98afa4762b8957f8aaa203c1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":440},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98ef60a159964d739c7f8acc0ccc8e3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":440},
                "size":{
                  "width":300,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cupons/u7.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9a7333d1cf4c4afcb329b61357a2b9cb":{
      "scriptId":"u0"},
    "573331fb8d804ea4881180d20b332507":{
      "scriptId":"u1"},
    "dd712d68ca234be389d07b5c35439a87":{
      "scriptId":"u2"},
    "7a9f6c13ce8a473393bbc57609d8bd14":{
      "scriptId":"u3"},
    "845c328ec60b4d3bba9560c9bf0da61a":{
      "scriptId":"u4"},
    "b4a4a288ca324afdb9eb324f586fc09a":{
      "scriptId":"u5"},
    "9e97fac2b1414e4e87ef7afd1551e78f":{
      "scriptId":"u6"},
    "293f0987ade74df6b3d7502975e0bc3e":{
      "scriptId":"u7"},
    "d801f217a0b848e7b35a64614fc0fe1d":{
      "scriptId":"u8"},
    "b15ad5972cbd48dba8bc378a4b3e5132":{
      "scriptId":"u9"},
    "d7441a67193a49eda660d9bc9d19bcfc":{
      "scriptId":"u10"},
    "62fdd26f81cf4a8cb4d358e6ea8e31ae":{
      "scriptId":"u11"},
    "bc04efe6fe7a43e198c8f692b532b7eb":{
      "scriptId":"u12"},
    "db0f3772b9284a01ad9f164e7f516842":{
      "scriptId":"u13"},
    "bf46cf4c81bf4ad09c2be25fe5f6ccd5":{
      "scriptId":"u14"},
    "4fe4db9de8c0448fb495bc481196d294":{
      "scriptId":"u15"},
    "9b6761e22d894c5f985f1506a9fa11af":{
      "scriptId":"u16"},
    "2e9ffae98afa4762b8957f8aaa203c1a":{
      "scriptId":"u17"},
    "98ef60a159964d739c7f8acc0ccc8e3f":{
      "scriptId":"u18"}}});